services:
   sparkhistory:
      image: ${SPARK_IMAGE}
      hostname: sparkhistory
      command: ["./init.sh"]
      ports:
#        - 18080:18080 # Spark History Server webui
      env_file:
        - ./compose-config
      environment:
        SPARK_HISTORY_OPTS: "-Dspark.history.fs.logDirectory=hdfs://namenode:9000/sparklog" # Spark log directory in HDFS
