services:
   namenode:
      image: ${HADOOP_IMAGE}
      hostname: namenode
      command: ["/bin/bash", "-c", "/opt/hadoop/resolve_HOSTs.py && hdfs namenode -format && hdfs namenode"]
      ports:
         - 50070:50070 # Namenode webui
      env_file:
        - ./compose-config
#      environment:
#          NAMENODE_INIT: "hdfs dfs -chmod 777 /"
#          ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
   datanode:
      command: ["/bin/bash", "-c", "/opt/hadoop/resolve_HOSTs.py && hdfs datanode"]
      hostname: datanode
      image: ${HADOOP_IMAGE}
      env_file:
        - ./compose-config
   resourcemanager:
      image: ${HADOOP_IMAGE}
      hostname: resourcemanager
      command: ["/bin/bash", "-c", "/opt/hadoop/resolve_HOSTs.py && yarn resourcemanager"]
      ports:
         - 8088:8088 # Yarn webui
      env_file:
        - ./compose-config
   nodemanager:
      image: ${HADOOP_IMAGE}
      hostname: nodemanager
      command: ["/bin/bash", "-c", "/opt/hadoop/resolve_HOSTs.py && yarn nodemanager"]
      env_file:
        - ./compose-config
