services:
   metastoredb:
     image: postgres
     environment:
       POSTGRES_USER: hive
       POSTGRES_PASSWORD: rootpwd
       POSTGRES_DB: metastore
   metastore:
     image: ${HIVE_IMAGE}
     command: ["hive","--service", "metastore"]
     env_file:
        - ./compose-config
   hiveserver2:
     image: ${HIVE_IMAGE}
     command: ["hive","--service", "hiveserver2"]
     environment:
        HADOOP_CONF_DIR: /opt/hive/conf
#     ports:
#        - 10002:10002 # HiveServer2 webui
     env_file:
        - ./compose-config
